spring:
  jpa:
     database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
management:
  cloudfoundry:
    enabled: true
    skip-ssl-validation: true
endpoints:
  health:
    show-details: true