ribbon:
  IsSecure: true
pivotal:
  quotesService:
    name: quotes
  userService:
    name: user
  accountsService:
    name: accounts
  portfolioService:
    name: portfolio
  analyticsService:
    name: analytics-service
logging:
  level:
     io:
        pivotal: DEBUG
     com:
        netflix: FATAL
     org:
        springframework:
           web: WARN
           cloud: WARN
spring:
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
