spring:
  zipkin:
    baseUrl: http://zipkin-server/
    sender:
      type: web
  cloud:
    cloudfoundry:
      skip-ssl-validation: true
    stream:
      rabbit:
        binder:
          use-ssl: false