spring:
  application:
     name: quotes-service
pivotal:
  quotes:
    quote_url: https://api.iextrading.com/1.0/stock/{symbol}/quote
    quotes_url: https://api.iextrading.com/1.0/stock/market/batch?symbols={symbols}&types=quote
    companies_url: http://dev.markitondemand.com/Api/v2/Lookup/json?input={name}
management:
  cloudfoundry:
    skip-ssl-validation: false

